[project]
name = "personal-website"
version = "0.1.0"
description = "Matthias Schoettle's personal website"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-git-revision-date-localized-plugin==1.2.9",
    "mkdocs-material==9.5.40",
]

[tool.uv]
dev-dependencies = [
    "pre-commit==4.0.1",
]
